[tool.black]
line-length = 120

[tool.isort]
known_local_folder = ["ai-assistant"]
length_sort = true
profile = "black"

[tool.ruff]
ignore = [
  "E501", # line too long, handled by black
]
ignore-init-module-imports = true
