import json

SUPPORTING_LANGUAGES = ["hy", "en", "ru"]

AVAILABLE_REGIONS = {
    "Kanaker_Zeytun_id": 4,
    "Malatia_Sebastia": 14,
    "Arabkir": 3,
    "Erebuni": 13,
    "1-6 Nork district": 10,
    "Charbakh": 9,
    "Nork-Marash": 7,
    "Center": 1,
    "Ajapnyak": 5,
    "Vahagni district": 18,
    "Large Center": 2,
    "Regions": 16,
    "Argavand": 15,
    "Davitashen": 6,
    "Avan, Avan-Arinj": 12,
    "7-9 Nork district": 11,
    "Shengavit": 8,
}

TRANSLATION_SAMPLES = {
    "price": {"hy": "Արժեքը", "ru": "Общая стоимость"},
    "total space": {"hy": "Մակերես", "ru": "Общая площадь"},
    "Purpose": {"hy": "Տարածքի նշանակությունը", "ru": "Назначение помещения"},
    "Office": {"hy": "Գրասենյակ", "ru": "Офис"},
    "Shop": {"hy": "Խանութ", "ru": "Магазин"},
    "Restaurant": {"hy": "Ռեստորան", "ru": "Ресторан"},
    "Others": {"hy": "Այլ", "ru": "Другие"},
    "rooms": {"hy": "Սենյակների քանակ", "ru": "Число комнат"},
    "Condition": {"hy": "Վիճակ", "ru": "Состояние"},
    "Not repaired": {"hy": "Պետ.վիճակ", "ru": "Без ремонта"},
    "Medium condition": {"hy": "Միջին վիճակ", "ru": "Средний ремонт"},
    "Fresh repaired": {"hy": "Կապիտալ վերանորոգված", "ru": "Капитальный ремонт"},
    "Building type": {"hy": "Տեսակը", "ru": "Тип"},
    "Stone": {"hy": "Քարե", "ru": "Каменный"},
    "Panel": {"hy": "Պանելային", "ru": "Панельный"},
    "Day price": {"hy": "Օրավարձ", "ru": "Стоимость за день"},
    "Mixed construction": {"hy": "Խառը կառուցապատման", "ru": "Общестроительное"},
    "Industrial": {"hy": "Արդյունաբերական", "ru": "Производственный"},
    "Stores": {"hy": "Հարկայն", "ru": "Этажность"},
    "Total square footage": {"hy": "Տարածքի մակ.", "ru": "Общая площадь участка"},
    "Total footage of the building": {"hy": "Շինության մակ.", "ru": "Площадь здания"},
    "Month price": {"hy": "Ամսավճար", "ru": "Стоимость за месяц"},
    "New buildings": {"hy": "Նորակառույց", "ru": "Новостройка"},
    "Target destination": {"hy": "Նպատակային նշանակությունը", "ru": "Целевое предназначение"},
    "For summer house": {"hy": "Այգեգործական", "ru": "под дачу"},
    "For commercial": {"hy": "Հասարակական", "ru": "ком.строй"},
    "For house building": {"hy": "Տնամերձ", "ru": "жил.строй"},
    "For agriculture": {"hy": "Գյուղատնտեսական", "ru": "сельхоз."},
    "Floor": {"hy": "Հարկ", "ru": "Этаж"},
}

INFORMATION_IDS = {
    "price": 38,
    "total_space": 12,
    "purpose": 44,
    "office": 49,
    "shop": 50,
    "restaurant": 51,
    "others": 52,
    "rooms": 11,
    "condition": 37,
    "not_repaired": 31,
    "medium_condition": 38,
    "fresh_repaired": 39,
    "building_type": 8,
    "stone": 7,
    "panel": 9,
    "new_building": 13,
    "floor": 10,
    "target_destination": 35,
    "for_summer_house": 23,
    "for_commercial": 24,
    "for_house_building": 25,
    "for_agriculture": 26,
    "mixed_construction": 27,
    "industrial": 28,
    "total_square_footage": 22,
    "total_footage_of_the_building": 15,
    "monthly_price": 39,
    "daily_price": 40,
}

INFORMATION_GATHERING_FORMAT = {
    "region": "region_id",
    "address": "address location",
    "sale": {
        "commercial_property": {
            "price": "number",
            "total_space": "decimal number",
            "purpose_options": "office/shop/Restaurant/others",
        },
        "apartment": {
            "price": "number",
            "rooms": "number",
            "total_space": "decimal_number",
            "condition_options": "not repaired/medium condition/Fresh repaired",
            "building_type_options": "stone/Panel/New buildings",
            "Floor": "Comma formatted",
        },
        "land": {
            "price": "number",
            "total_space": "decimal number",
            "target_destination_options": "For summer house/For commercial/For house building/For agriculture/Mixed construction/Industrial",
        },
        "house": {
            "price": "number",
            "stores": "number",
            "total_square_footage": "decimal number",
            "total_footage_of_the_building": "decimal number",
            "rooms": "number",
            "condition_options": "Not repaired/Medium condition/Fresh repaired",
        },
    },
    "Rent": {
        "commercial_property": {
            "monthly_price": "number",
            "total_space": "decimal number",
            "purpose_options": "office/shop/restaurant/others",
        },
        "apartment": {
            "day_price": "number",
            "Month_price": "number",
            "rooms": "number",
            "condition_options": "not repaired/medium condition/fresh repaired",
            "build_type_options": "stone/panel/new building",
            "floor": "comma formatted",
        },
        "house": {
            "daily_price": "number",
            "monthly_price": "number",
            "total_square_footage": "decimal number",
            "total_footage_of_the_building": "decimal number",
            "condition_options": "not repaired/medium condition/fresh repaired",
        },
    },
}

SAMPLE = {
    "region": "region_id",
    "address": "address location",
    "sale": {
        "apartment": {
            "price": "number",
            "rooms": "number",
            "total_space": "decimal_number",
            "condition_options": "not repaired/medium condition/Fresh repaired",
            "building_type_options": "stone/Panel/New buildings",
            "Floor": "Comma formatted",
        }
    },
}

ARMENIAN_TRANSLITERATION = {
    "ց": {"c": 0.8, "ts": 0.2},
    "ր": {"r": 1},
    "փ": {"p": 1},
    "ւ": {"v": 1},
    "օ": {"o": 1},
    "ք": {"q": 0.7, "k": 0.3},
    "և": {"ev": 0.7, "yev": 0.3},
    "ֆ": {"f": 1},
    "ՈՒ": {"U": 1},
    "Ու": {"U": 1},
    "ու": {"u": 1},
    "Ա": {"A": 1},
    "Գ": {"G": 1},
    "Բ": {"B": 1},
    "Ե": {"Ye": 0.1, "YE": 0.1, "E": 0.8},
    "Դ": {"D": 1},
    "Է": {"E": 1},
    "Զ": {"Z": 1},
    "Թ": {"T": 0.9, "Th": 0.05, "TH": 0.05},
    "Ը": {"Y": 0.35, "@": 0.45, "E": 0.2},
    "Ի": {"I": 1},
    "Ժ": {"ZH": 0.15, "J": 0.5, "Zh": 0.15, "G": 0.2},
    "Խ": {"Gh": 0.05, "X": 0.7, "Kh": 0.1, "KH": 0.1, "GH": 0.05},
    "Լ": {"L": 1},
    "Կ": {"K": 1},
    "Ծ": {"C": 0.3, "&": 0.1, "TS": 0.3, "Ts": 0.3},
    "Ձ": {"Dz": 0.4, "Z": 0.1, "DZ": 0.4, "D": 0.1},
    "Հ": {"H": 1},
    "Ճ": {"CH": 0.2, "Ch": 0.2, "J": 0.4, "Tch": 0.1, "C": 0.1},
    "Ղ": {"X": 0.5, "Gh": 0.25, "GH": 0.25},
    "Յ": {"Y": 0.9, "J": 0.1},
    "Մ": {"M": 1},
    "Շ": {"SH": 0.4, "Sh": 0.4, "S": 0.2},
    "Ն": {"N": 1},
    "Չ": {"4": 0.2, "CH": 0.3, "Ch": 0.4, "C": 0.1},
    "Ո": {"O": 1},
    "Ջ": {"Dj": 0.05, "J": 0.6, "DJ": 0.05, "G": 0.3},
    "Պ": {"P": 1},
    "Ս": {"S": 1},
    "Ռ": {"R": 1},
    "Տ": {"T": 1},
    "Վ": {"V": 1},
    "Ց": {"C": 0.8, "TS": 0.1, "Ts": 0.1},
    "Ր": {"R": 1},
    "Փ": {"P": 1},
    "Ւ": {"V": 1},
    "Օ": {"O": 1},
    "Ք": {"Q": 0.7, "K": 0.3},
    "Ֆ": {"F": 1},
    "ա": {"a": 1},
    "գ": {"g": 1},
    "բ": {"b": 1},
    "ե": {"ye": 0.2, "e": 0.8},
    "դ": {"d": 1},
    "է": {"e": 1},
    "զ": {"z": 1},
    "թ": {"t": 0.9, "th": 0.1},
    "ը": {"y": 0.35, "@": 0.45, "e": 0.2},
    "ի": {"i": 1},
    "ժ": {"j": 0.5, "zh": 0.3, "g": 0.2},
    "խ": {"x": 0.7, "kh": 0.2, "gh": 0.1},
    "լ": {"l": 1},
    "կ": {"k": 1},
    "ծ": {"c": 0.3, "ts": 0.6, "&": 0.1},
    "ձ": {"z": 0.1, "dz": 0.8, "d": 0.1},
    "հ": {"h": 1},
    "ճ": {"ch": 0.4, "c": 0.1, "j": 0.4, "tch": 0.1},
    "ղ": {"x": 0.5, "gh": 0.5},
    "յ": {"y": 0.9, "j": 0.1},
    "մ": {"m": 1},
    "շ": {"sh": 0.8, "s": 0.2},
    "ն": {"n": 1},
    "չ": {"4": 0.2, "ch": 0.7, "c": 0.1},
    "ո": {"o": 1},
    "ջ": {"j": 0.6, "dj": 0.1, "g": 0.3},
    "պ": {"p": 1},
    "ս": {"s": 1},
    "ռ": {"r": 1},
    "տ": {"t": 1},
    "վ": {"v": 1},
}

AVAILABLE_REGIONS_STR = json.dumps(AVAILABLE_REGIONS).replace("{", "{{").replace("}", "}}")

TRANSLATION_SAMPLES_STR = json.dumps(TRANSLATION_SAMPLES).replace("{", "{{").replace("}", "}}")

INFORMATION_IDS_STR = json.dumps(INFORMATION_IDS).replace("{", "{{").replace("}", "}}")

INFORMATION_GATHERING_FORMAT_STR = json.dumps(INFORMATION_GATHERING_FORMAT).replace("{", "{{").replace("}", "}}")

SAMPLE_STR = json.dumps(SAMPLE).replace("{", "{{").replace("}", "}}")

ARMENIAN_TRANSLITERATION_STR = json.dumps(ARMENIAN_TRANSLITERATION).replace("{", "{{").replace("}", "}}")
